name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build with PyInstaller
        run: |
          python build.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-artifact
          path: ./dist/

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git Identity
        run: |
          git config --global user.name "Edward Birchall"
          git config --global user.email "edbirchy664@gmail.com"
        shell: bash
        
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: app-artifact

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./dist/*  # Include any other files you want in the release
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Release
        run: |
          echo "Release ID: ${{ steps.create_release.outputs.id }}"
        # You can add additional steps here if needed
